service: individuell-examination-shui

provider:
  name: aws
  runtime: nodejs18.x  
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"  
  httpApi:
    cors:
      allowedOrigins:
        - '*'  
      allowedMethods:
        - GET
        - POST
        - PUT
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token

functions:
  createMessage:
    handler: functions/createMessage.handler
    events:
      - http:
          path: messages
          method: post

  getAllMessages:
    handler: functions/getAllMessages.handler
    events:
      - http:
          path: messages
          method: get

  getMessagesByUsername:
    handler: functions/getMessagesByUsername.handler
    events:
      - http:
          path: messages/by-username
          method: get
          request:
            parameters:
              querystrings:
                username: true

  updateMessage:
    handler: functions/updateMessage.handler
    events:
      - http:
          path: messages/{id}
          method: put

resources:
  Resources:
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: messages-table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: username-index
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
